# Generated by Django 3.0.7 on 2020-06-22 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=120, verbose_name='Тег title')),
                ('seo_description', models.TextField(max_length=500, verbose_name='Тег description')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('menu_title', models.CharField(max_length=120, verbose_name='Заголовок в меню')),
                ('slug', models.SlugField(unique=True, verbose_name='Урл')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=120, verbose_name='Тег title')),
                ('seo_description', models.TextField(max_length=500, verbose_name='Тег description')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('menu_title', models.CharField(max_length=120, verbose_name='Заголовок в меню')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Урл')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=120, verbose_name='Тег title')),
                ('seo_description', models.TextField(max_length=500, verbose_name='Тег description')),
                ('title', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Урл')),
                ('intro_text', models.TextField(verbose_name='Анонс')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Фото')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('featured', models.BooleanField(blank=True, default=False, null=True, verbose_name='Избранная в ТОП')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.Category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('moderated', models.BooleanField(default=False, verbose_name='Отмодерирован')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
